"""Static content contract for reconstruction-impact reports and notebooks.

The contract names the reader-facing nodes and connects them to the existing
scientific question records.  It does not define or run a scientific
calculation.
"""

from __future__ import annotations


SCOPES = ("Fibroblast", "Mono_Macro", "T")
LAYERS = ("foundation", "overall", "localization", "region")

QUESTION_LAYERS = {
    "foundation": "foundation",
    "complexity": "overall",
    "matched_k": "overall",
    "moran_all_valid": "overall",
    "moran_shared_valid": "overall",
    "emt_coverage": "overall",
    "emt_score": "overall",
    "anatomy": "localization",
    "changed_units": "localization",
    "emt_spatial_fields": "localization",
    "window_support": "localization",
    "local_vs_raw_leiden": "localization",
    "local_vs_raw_level2": "localization",
    "threshold_reliability": "region",
    "region_extent": "region",
    "scale_sensitivity": "region",
}

QUESTION_LABELS = {
    "foundation": ("比较基础", "Comparison foundation"),
    "complexity": ("复杂度变化", "Partition complexity"),
    "matched_k": ("匹配 K", "Matched K"),
    "moran_all_valid": ("Moran：各自有效基因", "Moran: all valid genes"),
    "moran_shared_valid": ("Moran：共享有效基因", "Moran: shared valid genes"),
    "emt_coverage": ("EMT 基因覆盖", "EMT gene coverage"),
    "emt_score": ("EMT 分数", "EMT scores"),
    "anatomy": ("解剖区域", "Anatomy context"),
    "changed_units": ("改变单元", "Changed units"),
    "emt_spatial_fields": ("EMT 空间场", "EMT spatial fields"),
    "window_support": ("窗口支持", "Window support"),
    "local_vs_raw_leiden": ("局部多样性：相对 Raw Leiden", "Local diversity vs Raw Leiden"),
    "local_vs_raw_level2": ("局部多样性：相对 Raw Level2", "Local diversity vs Raw Level2"),
    "threshold_reliability": ("阈值可靠性", "Threshold reliability"),
    "region_extent": ("区域范围", "Region extent"),
    "scale_sensitivity": ("尺度敏感性", "Scale sensitivity"),
}


def _spec(
    node_id: str,
    layer: str,
    title_zh: str,
    title_en: str,
    purpose_zh: str,
    purpose_en: str,
    method: tuple[str, str],
    questions: tuple[str, ...],
) -> dict[str, object]:
    return {
        "node_id": node_id,
        "layer": layer,
        "title_zh": title_zh,
        "title_en": title_en,
        "purpose_zh": purpose_zh,
        "purpose_en": purpose_en,
        "method": method,
        "questions": questions,
        "reading_placement": "audit" if layer == "foundation" else (
            "reference" if node_id == "2.3" else "main"
        ),
    }


NODE_SPECS = (
    _spec(
        "1.1",
        "foundation",
        "载体与路线语义",
        "Carrier and route semantics",
        "说明 Raw、Recon、空间/表达载体和 Reference 的来源及解释边界。",
        "Define the sources and interpretation boundaries of Raw, reconstructed, spatial, expression, and reference carriers.",
        ("input-views.md", "comparison-foundation"),
        ("foundation",),
    ),
    _spec(
        "1.2",
        "foundation",
        "比较范围与细胞类型",
        "Comparison scope and cell types",
        "固定三类 parent、输入纳入排除、抽样范围和各分析分母。",
        "Fix the three parent scopes, input inclusion and exclusion, sampling range, and analysis denominators.",
        ("input-views.md", "cohort-presentation"),
        ("foundation",),
    ),
    _spec(
        "1.3",
        "foundation",
        "配对与空间坐标",
        "Pairing and spatial coordinates",
        "核查 Raw/Recon ID、坐标来源、单位、一致性和空间覆盖。",
        "Check Raw/reconstruction IDs, coordinate provenance, units, consistency, and spatial coverage.",
        ("input-views.md", "pairing-presentation"),
        ("foundation",),
    ),
    _spec(
        "1.4",
        "foundation",
        "表达视图与完整基因空间",
        "Expression views and full gene space",
        "说明两侧表达层、完整基因范围及未测量、零值和不可计算的区别。",
        "Describe both expression views and the full gene range, separating unmeasured, zero, and non-computable states.",
        ("input-views.md", "gene-space-presentation"),
        ("foundation",),
    ),
    _spec(
        "1.5",
        "foundation",
        "分析专用预处理",
        "Analysis-specific preprocessing",
        "区分 Partition、Moran 和 EMT 各自的输入与预处理条件。",
        "Separate the input and preprocessing conditions for Partition, Moran, and EMT.",
        ("input-views.md", "preprocessing-presentation"),
        ("foundation",),
    ),
    _spec(
        "1.6",
        "foundation",
        "本层结论",
        "Foundation conclusion",
        "汇总已知比较条件和限制传递，只引用已审阅记录。",
        "Summarize known comparison conditions and propagated limits using only reviewed records.",
        ("outputs-and-test-plan.md", ""),
        ("foundation",),
    ),
    _spec(
        "2.1",
        "overall",
        "分群复杂度",
        "Partition complexity",
        "描述路线内 Raw/Recon 的分群数量、大小、结构及选择诊断。",
        "Describe Raw/reconstruction cluster counts, sizes, structure, and selection diagnostics within a route.",
        ("impact-analysis.md", "partition-complexity"),
        ("complexity",),
    ),
    _spec(
        "2.2",
        "overall",
        "控制复杂度后的归属变化",
        "Assignment change after complexity control",
        "先核查 matched-K，再读取 mapping、contingency、change fraction 和 ARI。",
        "Check matched-K first, then read the saved mapping, contingency, change fraction, and ARI.",
        ("impact-analysis.md", "matched-k"),
        ("matched_k",),
    ),
    _spec(
        "2.3",
        "overall",
        "哪些 cell type 涉及变化",
        "Which cell types show change",
        "并列三个 parent 的已有结果，保留各自分母和 matched-K 条件。",
        "Place the three parent results side by side while retaining their denominators and matched-K conditions.",
        ("impact-analysis.md", "matched-k"),
        ("matched_k", "changed_units"),
    ),
    _spec(
        "2.4",
        "overall",
        "全基因空间自相关：Moran",
        "Full-gene spatial autocorrelation: Moran",
        "分开比较各自有效基因分布与共同有效基因的逐基因变化。",
        "Separate side-specific valid-gene distributions from gene-wise changes over shared valid genes.",
        ("gene-and-function.md", "moran"),
        ("moran_all_valid", "moran_shared_valid"),
    ),
    _spec(
        "2.5",
        "overall",
        "EMT：资源覆盖与评分",
        "EMT: resource coverage and scores",
        "分别记录资源命中、coverage、cutoff、score 分布和配对变化。",
        "Record resource hits, coverage, cutoffs, score distributions, and paired changes separately.",
        ("gene-and-function.md", "emt-coverage"),
        ("emt_coverage", "emt_score"),
    ),
    _spec(
        "2.6",
        "overall",
        "总体变化结论",
        "Overall conclusion",
        "并列结构、Moran 和 EMT 的已保存结果，不合成改善总分。",
        "Set the saved structural, Moran, and EMT results alongside one another without an improvement score.",
        ("outputs-and-test-plan.md", ""),
        ("complexity", "matched_k", "moran_all_valid", "moran_shared_valid", "emt_coverage", "emt_score"),
    ),
    _spec(
        "3.1",
        "localization",
        "Anatomy 背景",
        "Anatomy context",
        "提供完整 Raw 的组织背景、覆盖和窗口支持条件。",
        "Provide full-Raw tissue context, coverage, and window-support conditions.",
        ("impact-analysis.md", "anatomy"),
        ("anatomy",),
    ),
    _spec(
        "3.2",
        "localization",
        "Assignment change 的空间位置",
        "Spatial location of assignment change",
        "复用已有 mapping 和 changed units，定位归属差异并保留控制条件。",
        "Reuse the saved mapping and changed units to locate assignment differences with their controls.",
        ("impact-analysis.md", "changed-units"),
        ("changed_units",),
    ),
    _spec(
        "3.3",
        "localization",
        "EMT 的空间位置",
        "Spatial location of EMT",
        "展示 Raw、Recon 和 paired delta 的 EMT 空间字段及其载体。",
        "Show Raw, reconstructed, and paired-delta EMT spatial fields with their carrier semantics.",
        ("gene-and-function.md", "emt-spatial-fields"),
        ("emt_spatial_fields",),
    ),
    _spec(
        "3.4",
        "localization",
        "局部状态比较的基础",
        "Foundation for local-state comparison",
        "固定两条 Raw baseline、窗口支持、尺度选择和共同 rarefaction draws。",
        "Fix the two Raw baselines, window support, scale choice, and common rarefaction draws.",
        ("impact-analysis.md", "window-support"),
        ("window_support",),
    ),
    _spec(
        "3.5",
        "localization",
        "Kobs：相对 Raw Leiden 与 Raw Level2",
        "Kobs: versus Raw Leiden and Raw Level2",
        "分别读取两条 Raw baseline 下的局部状态数量变化。",
        "Read local state-count changes separately against the two Raw baselines.",
        ("impact-analysis.md", "local-diversity"),
        ("local_vs_raw_leiden", "local_vs_raw_level2"),
    ),
    _spec(
        "3.6",
        "localization",
        "Neff：相对 Raw Leiden 与 Raw Level2",
        "Neff: versus Raw Leiden and Raw Level2",
        "分别读取两条 Raw baseline 下的有效状态多样性变化。",
        "Read effective state-diversity changes separately against the two Raw baselines.",
        ("impact-analysis.md", "local-diversity"),
        ("local_vs_raw_leiden", "local_vs_raw_level2"),
    ),
    _spec(
        "3.7",
        "localization",
        "Evenness：辅助解释",
        "Evenness: supporting interpretation",
        "用 evenness 辅助解释 richness 和组成，不预设越高越好。",
        "Use evenness to support richness and composition interpretation without assuming that higher is better.",
        ("impact-analysis.md", "local-diversity"),
        ("local_vs_raw_leiden", "local_vs_raw_level2"),
    ),
    _spec(
        "3.8",
        "localization",
        "Anatomy 分层的局部结果",
        "Anatomy-stratified local results",
        "按 anatomy 分层呈现局部指标、delta 和各自分母。",
        "Present local metrics, deltas, and denominators by anatomy stratum.",
        ("impact-analysis.md", "local-diversity"),
        ("anatomy", "local_vs_raw_leiden", "local_vs_raw_level2"),
    ),
    _spec(
        "3.9",
        "localization",
        "空间定位与局部状态结论",
        "Localization and local-state conclusion",
        "分开归纳 assignment、EMT 和局部多样性空间证据，衔接 Region。",
        "Summarize assignment, EMT, and local-diversity spatial evidence separately before Region.",
        ("outputs-and-test-plan.md", ""),
        ("anatomy", "changed_units", "emt_spatial_fields", "window_support", "local_vs_raw_leiden", "local_vs_raw_level2"),
    ),
    _spec(
        "4.1",
        "region",
        "可识别性与阈值可靠性",
        "Identifiability and threshold reliability",
        "先检查阈值区间、bootstrap 比例、窗口支持和最终状态。",
        "Check threshold intervals, bootstrap fraction, window support, and final status first.",
        ("impact-analysis.md", "region-reliability"),
        ("threshold_reliability",),
    ),
    _spec(
        "4.2",
        "region",
        "连续状态与 State Region",
        "Continuous state and State Region",
        "区分 Recon Neff 连续场、可识别 mask 和不可识别状态。",
        "Separate the reconstructed Neff field, identifiable mask, and non-identifiable state.",
        ("impact-analysis.md", "region-extent"),
        ("region_extent",),
    ),
    _spec(
        "4.3",
        "region",
        "Region 覆盖",
        "Region coverage",
        "报告 Overall 与 anatomy 分层的面积、窗口和 unit 分母。",
        "Report area, window, and unit denominators for Overall and anatomy strata.",
        ("impact-analysis.md", "region-extent"),
        ("region_extent",),
    ),
    _spec(
        "4.4",
        "region",
        "尺度敏感性",
        "Scale sensitivity",
        "检查局部 rarefied 指标和 delta 随候选尺度的变化。",
        "Check how local rarefied metrics and deltas change across candidate scales.",
        ("impact-analysis.md", "scale-sensitivity"),
        ("scale_sensitivity",),
    ),
    _spec(
        "4.5",
        "region",
        "Region 结论",
        "Region conclusion",
        "在可靠性、状态和覆盖条件下说明 Region 能支持的解释。",
        "State what Region can support under its reliability, state, and coverage conditions.",
        ("outputs-and-test-plan.md", ""),
        ("threshold_reliability", "region_extent", "scale_sensitivity"),
    ),
    _spec(
        "summary",
        "summary",
        "跨 parent 综合解释",
        "Cross-parent interpretation",
        "并列各科学问题的支持、不支持或无法判断，保留条件和证据入口。",
        "Place support, non-support, and uncertainty for each scientific question side by side with conditions and evidence links.",
        ("outputs-and-test-plan.md", ""),
        tuple(QUESTION_LAYERS),
    ),
)
